### ISSUE TITLE
Failed to install the dependencies using pip

### ISSUE THREAD

**Issue by merdan-9** [Henry1iu/TNT-Trajectory-Prediction#24]
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/build/80754af9/pillow_1617383569452/work'

Maybe you need to populate the requirements.txt file manually?

**Comment by vishweshvhavle** [comment]
Try `pip install pillow==9.9.1`
Then edit out the requirement from requirement.txt

**Comment by Henry1iu** [comment]
Hi, 

I have modified the requirements.txt accordingly. Thanks for reminding me. 

Best regards,
Jianbang

**Comment by vishweshvhavle** [comment]
`9.1.0` not `9.9.1,` my bad

**Comment by Henry1iu** [comment]
> `9.1.0` not `9.9.1,` my bad

That's ok. I have modified the file accordingly.  :)

**Comment by Henry1iu** [comment]
> ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/build/80754af9/pillow_1617383569452/work'
> 
> Maybe you need to populate the requirements.txt file manually?

Also, the configuration of the torch_geometric (version 1.7.2) is a little bit tricky. I recommend you configure the pytorch and torch_geometric before installing other dependencies. In fact, these are two of the most important libraries.
