### ISSUE TITLE
Smoothness of predicted trajectories

### ISSUE THREAD

**Issue by vishweshvhavle** [Henry1iu/TNT-Trajectory-Prediction#25]
I visualized the predicted trajectories. Are the trajectories supposed to be this way or am I doing something wrong?
![2645](https://user-images.githubusercontent.com/52754207/180938799-13b0378a-a200-4fc8-a33f-5e37589090df.png)
![3700](https://user-images.githubusercontent.com/52754207/180938806-585621f8-f805-4854-b7e7-112977c4d2a6.png)
![3828](https://user-images.githubusercontent.com/52754207/180938810-40032f03-2dad-4739-83c1-73af8e129de6.png)
![3861](https://user-images.githubusercontent.com/52754207/180938813-f30f4139-9243-4e0b-ab66-3fe74bd3d5f6.png)
![4791](https://user-images.githubusercontent.com/52754207/180938814-189a8202-21e7-4d77-82fa-30322122707d.png)
Agent: Yellow
Predictions: Red
AV and Other Agents: Blue

**Comment by alfredgu001324** [comment]
Hi @vishweshvhavle , sorry for bothering you after a long time. I am wondering how you get rid of the s's and e's that are shown along the lanes when visualizing the road. Are you using the 'from argoverse.utils.mpl_plotting_utils import visualize_centerline' when plotting out the graph? 
Thank you so much!

**Comment by MPCheng-ZW** [comment]
Hi, @vishweshvhavle. I am sorry for bothering you. Can you share your visualization code with me? Thanks!
Hi, @alfredgu001324. Have you produced the visualization results yet? Thank you!
