### ISSUE TITLE
Process is killed when transforming to Graph Data

### ISSUE THREAD

**Issue by alfredgu001324** [Henry1iu/TNT-Trajectory-Prediction#36]
Hi,

Thanks for sharing this great repo. I have finished the data pre-processing. However, when I tried to run the train_tnt.py using interm_data, the "Transforming the data to GraphData..." process always stopped at 77% and the program got killed. I am wondering what might be the cause of this? I have checked that I still have 100GB of free space available so the disk space should not be the issue? When I run the train_tnt.py using the interm_data_small, everything is just fine. 

Thank you so much for your help and looking forward to your reply.

**Comment by Henry1iu** [comment]
Hi,

Thanks for your appreciation. I think it may be caused by the limitation of memory. 
What's your memory size (memory + swap)? The transformation consumes a large memory space (128G+).

**Comment by Wei233666** [comment]
Hello!
I use the server memory 250G+, why run to about 50% will stop
