### ISSUE TITLE
Question about test dataset in intem_data_small

### ISSUE THREAD

**Issue by kukulinxin** [Henry1iu/TNT-Trajectory-Prediction#51]
在使用你给的interm_data_small 数据集进行测试时，发现在可视化部分真实轨迹的的位置貌似是不变的，想问问这是什么原因呢？希望能得到你的解答，感谢。
第一张图是 data.y.unsqueeze(1)的输出。
第二张图是某一个gt_trajectories的输出，我的理解其应当是一个30大小的轨迹序列。
![微信图片_20230806170334](https://github.com/Henry1iu/TNT-Trajectory-Prediction/assets/114294307/216e4e8e-7292-4fab-8ab4-f3f604bc52c5)
![微信图片_20230806170408](https://github.com/Henry1iu/TNT-Trajectory-Prediction/assets/114294307/056803b4-c3fb-48fe-b541-e456e7435a5e)

**Comment by Henry1iu** [comment]
官方发布的测试数据集没有预测真值，详情请参考官方数据

**Comment by kukulinxin** [comment]
> 官方发布的测试数据集没有预测真值，详情请参考官方数据
好的，感谢。
